# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/
  #相册: /instagram

# SubNav
subnav:
  # github: "https://github.com/litten"
  # weibo: "http://weibo.com/litten225"
  rss: /atom.xml
  # facebook: "/"
  # google: "/"
  # twitter: "/"
  # linkedin: "/"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous

favicon: /favicon.png

avatar: /statics/images/logo.jpg
share: true
duoshuo: "xianyunyehe"
tagcloud: true

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: false